import ArrowButton from "@/components/ArrowButton";
import Page from "@/components/Page";
import PageTitle from "@/components/PageTitle";
import capitalize from "@/utils/capitalize";
import Head from "next/head";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useRouter } from "next/router";
import Link from "next/link";
import OutlineButton from "@/components/OutlineButton";
import Paragraph from "@/components/Paragraph";
import strapiApi from "@/lib/strapi";
import { ArticleData } from "@/types/strapi.type";

interface StaticProps {
  locale: string;
}
export async function getStaticProps({ locale }: StaticProps) {
  const articlesResponse = await strapiApi.getArticles();
  return {
    props: {
      articles: articlesResponse.data.map(
        (articleResponse) => articleResponse.attributes
      ),
      ...(await serverSideTranslations(locale, ["articles"])),
      // Will be passed to the page component as props
    },
  };
}

interface ArticleCardProps {
  article: ArticleData;
}
function ArticleCard({ article }: ArticleCardProps) {
  console.table(article);
  return (
    <div className="flex justify-center my-5">
      <Link className="block w-2/3" href="#">
        <OutlineButton>
          <Paragraph>{article.title}</Paragraph>
        </OutlineButton>
      </Link>
    </div>
  );
}

interface ArticlesProps {
  articles: ArticleData[];
}
export default function Articles({ articles }: ArticlesProps) {
  const { t } = useTranslation("articles");
  const router = useRouter();

  const title = "Eflamm - " + capitalize(t("articles"));

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <div className="flex flex-row items-end -ml-6">
          <div className="-mb-1 sm:mb-0">
            <ArrowButton
              direction="left"
              shape="square"
              onClick={() => router.push("/")}
            />
          </div>
          <PageTitle>{capitalize(t("articles"))}</PageTitle>
        </div>
        {articles.map((article) => (
          <ArticleCard key={article.slug} article={article} />
        ))}
        <div className="h-20" />
        <div className="fixed bottom-2 sm:bottom-10">
          <ArrowButton
            direction="left"
            shape="rectangular"
            onClick={() => router.push("/")}
          />
        </div>
      </Page>
    </>
  );
}
