import Head from "next/head";
import { PropsWithChildren, useEffect, useState } from "react";
import Link from "next/link";

import styles from "@/styles/Home.module.css";
import Page from "@/components/Page";

interface MainTitleProps {
  title: string;
}

const MainTitle = ({ title }: MainTitleProps) => {
  const arrName = Object.assign([], title.toUpperCase());
  const alternatePosition = (index: number) => {
    return index % 2 ? " mt-16 sm:mt-40 md:mt-16 lg:mt-20 xl:mt-46 " : "";
  };
  return (
    <div className="w-full h-1/6 sm:h-4/6 ">
      <p
        className={
          styles.mainTitleFont +
          " w-full flex justify-center items-center text-sizeable lg:text-enormous xl:text-gargantua text-transparent bg-clip-text bg-gradient-to-br from-primary to-primaryGradient "
        }
      >
        {arrName.map((letter: string, index: number) => (
          <span
            className={
              " -mx-0 md:mx-4 lg:mx-5 xl:mx-6" + alternatePosition(index)
            }
            key={Math.random()}
          >
            {letter}
          </span>
        ))}
      </p>
    </div>
  );
};

interface IntroductionProps {
  text: string;
}

const Introduction = ({ text }: IntroductionProps) => {
  const [index, setIndex] = useState(0);
  const [textToDisplay, setTextToDisplay] = useState("");
  useEffect(() => {
    setTextToDisplay(text.slice(0, index));
    setTimeout(() => {
      setIndex(index + 1);
    }, 33);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [index]);

  return (
    <div className="w-11/12 lg:w-4/6 h-1/6 flex items-start">
      <p
        className={
          "font-mono text-sm sm:text-base text-secondary whitespace-pre-wrap drop-shadow-white "
        }
      >
        {textToDisplay}
        <span
          className={
            styles.caret +
            " ml-1 " +
            (text.length === textToDisplay.length ? styles.caretBlinking : "")
          }
        />
      </p>
    </div>
  );
};

function Menu(props: PropsWithChildren) {
  return (
    <div className="w-11/12 sm:w-4/5 h-2/6 sm:h-1/6 flex items-center sm:items-end justify-around flex-col sm:flex-row pb-10 font-mono text-xl sm:text-3xl tracking-wide sm:tracking-wider text-orange-300 drop-shadow-white">
      {props.children}
    </div>
  );
}

export default function Home() {
  const introductionText = `> Ce site est en cours de construction, vous pourrez bientôt retrouver les sections suivantes :
  - mes expériences professionnelles
  - des articles sur le développement
  - des articles sur mes activités en dehors du développement
  - des informations à propos de ce site
  - les moyens de me joindre`;
  return (
    <>
      <Head>
        <title>Eflamm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <MainTitle title="Eflamm" />
        <Introduction text={introductionText} />
        <Menu>
          <Link href="/experiences">Expériences</Link>
          <Link className="text-disabled cursor-not-allowed" href="#">
            Articles
          </Link>
          <Link className="text-disabled cursor-not-allowed" href="#">
            Blog
          </Link>
          <Link className="text-disabled cursor-not-allowed" href="#">
            A propos
          </Link>
        </Menu>
      </Page>
    </>
  );
}
