import Head from "next/head";
import { PropsWithChildren, useEffect, useState } from "react";
import Link from "next/link";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import styles from "@/styles/Home.module.css";
import Page from "@/components/Page";
import Paragraph from "@/components/Paragraph";

interface StaticProps {
  locale: string;
}
export async function getStaticProps({ locale }: StaticProps) {
  console.log("locale : " + locale);
  return {
    props: {
      ...(await serverSideTranslations(locale, ["home"])),
      // Will be passed to the page component as props
    },
  };
}

interface MainTitleProps {
  title: string;
}

const MainTitle = ({ title }: MainTitleProps) => {
  const arrName = Object.assign([], title.toUpperCase());
  const alternatePosition = (index: number) => {
    return index % 2 ? " mt-16 sm:mt-40 md:mt-16 lg:mt-20 xl:mt-46 " : "";
  };
  return (
    <div className="w-full h-1/6 sm:h-4/6 ">
      <p
        className={
          styles.mainTitleFont +
          " w-full flex justify-center items-center text-sizeable lg:text-enormous xl:text-gargantua text-transparent bg-clip-text bg-gradient-to-br from-primary to-primaryGradient "
        }
      >
        {arrName.map((letter: string, index: number) => (
          <span
            className={
              " -mx-0 md:mx-4 lg:mx-5 xl:mx-6" + alternatePosition(index)
            }
            key={Math.random()}
          >
            {letter}
          </span>
        ))}
      </p>
    </div>
  );
};

interface IntroductionProps {
  text: string;
}

const Introduction = ({ text }: IntroductionProps) => {
  const [index, setIndex] = useState(0);
  const [textToDisplay, setTextToDisplay] = useState("");
  useEffect(() => {
    setTextToDisplay(text.slice(0, index));
    setTimeout(() => {
      setIndex(index + 1);
    }, 33);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [index]);

  return (
    <div className="w-11/12 lg:w-4/6 h-1/6 flex items-start">
      <Paragraph>
        {textToDisplay}
        <span
          className={
            styles.caret +
            " ml-1 " +
            (text.length === textToDisplay.length ? styles.caretBlinking : "")
          }
        />
      </Paragraph>
    </div>
  );
};

function Menu(props: PropsWithChildren) {
  return (
    <div className="w-11/12 sm:w-4/5 h-2/6 sm:h-1/6 flex items-center sm:items-end justify-around flex-col sm:flex-row pb-10 font-mono text-xl sm:text-3xl capitalize tracking-wide sm:tracking-wider text-orange-300 drop-shadow-white">
      {props.children}
    </div>
  );
}

export default function Home() {
  const { t } = useTranslation("home");

  return (
    <>
      <Head>
        <title>Eflamm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page align="center">
        <MainTitle title="Eflamm" />
        <Introduction text={t("introduction")} />
        <Menu>
          <Link href="/experiences">{t("experiences")}</Link>
          <Link className="text-disabled cursor-not-allowed" href="#">
            {t("articles")}
          </Link>
          <Link className="text-disabled cursor-not-allowed" href="#">
            {t("blog")}
          </Link>
          <Link href="/about">{t("about")}</Link>
        </Menu>
      </Page>
    </>
  );
}
